databases:
  - name: Database
    plan: free
    region: oregon

services:
  - type: web
    name: Backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: ${{ Database.DATABASE_URL }}

  - type: web
    name: Frontend
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: ${{ Backend.serviceUrl }}
