databases:
  - name: postgres-db
    plan: free
    region: oregon

services:
  - type: web
    name: Backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: ${{ postgres-db.DATABASE_URL }} # Render injects this automatically

  - type: web
    name: Frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    plan: free
    autoDeploy: true
    dependsOn:
      - Backend
    dockerBuildArgs:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-cs50x-prompter.onrender.com
